### ISSUE TITLE
Question on Lecture 11 Factorization

### ISSUE THREAD

**Issue by chowerth** [JuliaAcademy/Introduction-to-Julia#7]
A little confused on why the assert is failing for me in the screenshot below. I believe it's due to floating point precision issues, but I'm curious how any notebook would pass if that's the case. To preface, I will also mention the assert for the eigenvalues passes fine. 

If I use the Diagonal constructor or diagm function I (seemingly) get the same result as the expected answer, but the assert still fails. Interestingly A_diag == A_diag2 returns true. Checking their types and using isdiag() suggests it should be equivalent? Even using the approximation comparison ≈ gives a false result.

Furthermore, it doesn't seem to be a problem for the lowertri comparison. It passes just fine.

![image](https://user-images.githubusercontent.com/56286587/141668824-17cf974e-dd83-46aa-ac17-7877df2b0b48.png)

Doing a subtraction I see there is difference in the final calculation so it must be a precision issue but then I figured it'd fail for everyone. It passes fine for the lowertri because they're just integers.

![image](https://user-images.githubusercontent.com/56286587/141669063-0491023e-45ce-4142-a12a-783e2434a002.png)

**Comment by logankilpatrick** [comment]
Hey! Mind posting this over on https://discourse.julialang.org? You will likely get an answer quickly there.
